export default PortCopy
import Card from "../Card"

function PortCopy(){

    return(
        <section className="main grid">
            <Card link="https://newordereditora.com/dying-earth/" imagem="/Images/capa-contos-dying-earth.jpg" titulo="Press Release - Jack Vance" descrição="5 de Dezembro de 2021 - Contos de Dying Earth, obra clássica do premiado escritor Jack Vance chega ao Brasil através do selo Dragão de Papel da Editora New Order. O título estará em pré-venda a partir da meia-noite do dia 05 de Dezembro de 2021 na loja da editora.de Dezembro de 2021 - Contos de Dying Earth, obra clássica do premiado escritor Jack Vance chega ao Brasil através do selo Dragão de Papel da Editora New Order. O título estará em pré-venda apartir da meia-noite do dia 05 de Dezembro de 2021 na loja da editora.de Dezembro de 2021 - Contos de Dying Earth, obra clássica do premiado escritor Jack Vance chega ao Brasil através do selo Dragão de Papel da Editora New Order. O título estará em pré-venda a partir da meia-noite do dia 05 de Dezembro de 2021 na loja da editora. "/>
            <Card link="https://newordereditora.com/a-trajetoria-de-shadowrun-na-new-order/" imagem="/Images/capa-shadowrun.jpg" titulo="Post - A Trajetória de Shadowrun na New Order" descrição="Uma breve história da relação da New Order Editora com Shadowrun, o RPG cyberpunk mais famoso do mundo. Do primeiro financiamento coletivo ao mais recente. "/>
            <Card link="http://cronistasdastrevasbr.com/review-ihunt-the-rpg-olivia-hill-e-filamena-young/" imagem="/Images/capa-ihunt.png" titulo="Review: iHunt the RPG - Olivia Hill e Filamena Young" descrição="Todos gostaríamos de imaginar que em um mundo com monstros nós seríamos bravos e destemidos caçadores. Agora, pense: o que realmente levaria uma pessoa como eu ou você arriscar a vida(!) para matar uma criatura que possui habilidades e capacidades sobrenaturais? Isso aí, desespero. Fome. Contas. Falta de perspectiva na vida. "/>
            <Card link="https://newordereditora.com/simples-e-divertido-meeple-up/" imagem="/Images/capa-meeple-up.png" titulo="Review - Simples e Divertido: Meeple Up" descrição="Chegou de mansinho e conquistou não apenas os corações do público mas também o do rigoroso júri técnico. Estamos falando de Meeple Up, o boardgame vencedor do concurso de protótipos realizado no Diversão Offline/SP 2018 em parceria com o Catarse - plataforma de financiamentos coletivos. "/>
            <Card link="https://newordereditora.com/numenera-antologia-de-aventuras/" imagem="/Images/capa-numenera-antologia.jpg" titulo="Post: Numenera - Antologia de Aventuras" descrição='Intrépidos aventureiros e exploradores do Nono Mundo, a espera acabou! Após enfrentarmos inúmeros desafios e contratempos, apresentamos uma Antologia Numenera revisada e expandida. Agora sob o selo The Last Order, responsável por publicar sucessos como "O Caminho do Mestre Cafeinado" de Rafael Balbi, a "Recursão Retrofuturista de Eneias Tavares" e "Epifania" de Marcelo Telles, temos o orgulho de lançar este compilado de aventuras escritas por alguns dos maiores nomes do RPG nacional.'/>
            <Card link="https://medium.com/@hiramalem/voc%C3%AA-recebe-pelo-que-paga-78aff095f045" imagem="/Images/umbra.png" titulo="Tradução - Você recebe pelo que paga" descrição="(Texto original da Olivia Hill - Tradução livre minha e autorizada pela autora) Os RPGs de mesa mainstream nunca vão melhorar de fato como uma forma de arte ou negócio enquanto profissionais experientes só forem pagos o valor que editoras indie oferecem para estranhos sem experiência. "/>
        </section>
    )
}